[package]
name = "optical_flow"
version = "0.1.0"
edition = "2021"

[features]
cuda = ["onnx/cuda"]
migraphx = ["onnx/migraphx"]

[dependencies]
image = { workspace = true }
ndarray = { workspace = true }
onnx = { path = "../onnx" }
log = { workspace = true }
anyhow = { workspace = true }
